name: plasticparcels
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - parcels>=3.0.2
  - shapely
  - geopandas


  # Formatting
  - black
  - isort

  # Testing
  - pytest
  - pytest-html
  - coverage

  # Linting
  - flake8>=2.1.0
  - pre_commit
  - pydocstyle

  # Docs
  - ipython
  - numpydoc
  - nbsphinx
  - sphinx<6
  - pandoc>1.12.1,<3
  - pydata-sphinx-theme
  - sphinx-autobuild
  - myst-parser
